### ISSUE TITLE
question: is it useful for ios apps/firmware disassembly?

### ISSUE THREAD

**Issue by daniel-bluesea** [maddiestone/IDAPythonEmbeddedToolkit#2]

**Comment by maddiestone** [comment]
Some of the scripts may be useful for different functions when reversing an iOS app or firmware, but in general this toolkit is geared more towards firmware images running on a micro-controller or micro-processor. Without more details of what would be "useful" to you, I can't fully answer the question. 

Feel free to take a look at the README & presentations to see how I've used the scripts for reversing embedded devices.
